services:
  template_manager:
        class: killoblanco\TemplateManagerBundle\Twig\Extension\TemplateManagerExtension
        public: true
        tags:
          - { name: twig.extension }
#    template_manager.example:
#        class: killoblanco\TemplateManagerBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
