<?php

namespace killoblanco\TemplateManagerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TemplateDefaultsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateDefaultsRepository extends EntityRepository
{
}
